title: Fraud analytics 
description: My Personal Stack Problems
author: Seonmin Kim (Ted Kim)
github: https://github.com/angrykim
about: I am a fraud analyst & machine learning engineer.
       <br>
       Keyword : Money laundering, Machine learning, Fraud analytics 

disqus_shortname: Fraud analytics 
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/seonmin/"
    - icon: fa-github
      link: "https://github.com/angrykim"

share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://angrykim.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

theme: jekyll-theme-minimal
